//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AccelerometerFilter : NSObject
{
    double x;
    double y;
    double z;
}

@property(readonly, nonatomic) double z; // @synthesize z;
@property(readonly, nonatomic) double y; // @synthesize y;
@property(readonly, nonatomic) double x; // @synthesize x;

@end

