//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ActionRecognition.h"

#import "UIAccelerometerDelegate-Protocol.h"

@class NSString;

@interface ActionRecognition (AccelerometerDelegate) <UIAccelerometerDelegate>
- (void)accelerometer:(id)arg1 didAccelerate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

