//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@protocol AnimationDelegateObjectDelegate;

@interface AnimationDelegateObject : MMObject
{
    id <AnimationDelegateObjectDelegate> m_delegate;
}

@property(nonatomic) __weak id <AnimationDelegateObjectDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;

@end

