//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ImageMessageNodeView.h"

@interface AppImageMessageNodeView : ImageMessageNodeView
{
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (_Bool)ifAppInfoAreaInContent;
- (id)getMoreMainInfomationAccessibilityDescription;
- (void)onForward:(id)arg1;
- (void)onCopy:(id)arg1;
- (id)thumbImage;
- (id)getMaskedMsgImgThumb:(id)arg1;
- (id)hdImagePath;
- (id)thumbImagePath;
- (id)maskedThumbImagePath;
- (void)showImage;

@end

