//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AppRecordMessageNodeView.h"

@class UILabel;

@interface AppNoteMessageNodeView : AppRecordMessageNodeView
{
    UILabel *m_TitleLabel;
    UILabel *m_ContentLabel;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)cutImage:(id)arg1 toFitSize:(struct CGSize)arg2;
- (void)updateBkgImage:(_Bool)arg1;
- (void)initSourceView;
- (int)getImgDataCount:(id)arg1;
- (id)getDisplayImgDatas:(id)arg1;
- (void)layoutSubviewsImgText:(id)arg1;
- (void)layoutSubviewsOnlyText:(id)arg1;
- (void)layoutSubviewsImgs:(id)arg1;
- (void)createDashLine;
- (void)layoutSubviewsInternal;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;

@end

