//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

@class MMProgressView, UILabel, UIView;

@interface AppWCCardMessageNodeView : BaseMessageNodeView
{
    UILabel *m_detailLabel;
    MMProgressView *m_progressView;
    UIView *m_progressBkgView;
    UILabel *titleLabel;
    UILabel *descLabel;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)getMoreMainInfomationAccessibilityDescription;
- (void)onMenuItemWillHide;
- (void)onTouchCancel;
- (void)onLongTouch;
- (void)onTouchUpInside;
- (void)onTouchDownRepeat;
- (void)onTouchDown;
- (void)onMoreOperate:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onFavoriteAdd:(id)arg1;
- (void)showOpearation;
- (void)onClick;
- (_Bool)ifShowAppInfo;
- (void)updateThumbImage;
- (void)updateBkgImage:(_Bool)arg1;
- (void)onClearResource;
- (void)onDisappear;
- (void)updateStatus:(id)arg1;
- (void)layoutSourceView;
- (void)layoutSubviewsInternal;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;

@end

