//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class UIFont;

@interface AttributeLabel : UILabel
{
    UIFont *_highlightTextFont;
}

@property(retain, nonatomic) UIFont *highlightTextFont; // @synthesize highlightTextFont=_highlightTextFont;
- (void).cxx_destruct;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 range:(struct _NSRange)arg3;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 startIndex:(unsigned long long)arg3;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2;
- (id)init;

@end

