//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AudioReceiver.h"

#import "DownloadVoiceDelegate-Protocol.h"

@interface AudioReceiver (DownloadVoiceDelegate) <DownloadVoiceDelegate>
- (void)OnRecvData:(id)arg1 MesLocalID:(unsigned int)arg2 n64MesSvrID:(long long)arg3 CreateTime:(unsigned int)arg4 VoiceTime:(unsigned int)arg5 Offset:(unsigned int)arg6 Len:(unsigned int)arg7 Data:(id)arg8 EndFlag:(unsigned int)arg9 ErrNo:(unsigned int)arg10;
@end

