//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AudioReceiver.h"

#import "SPXAudioPlayerDelegate-Protocol.h"

@interface AudioReceiver (SPXAudioPlayerDelegate) <SPXAudioPlayerDelegate>
- (_Bool)OnSPXEndDontNotifyOtherApp;
- (void)OnSPXEarTip;
- (void)OnSPXEndPlaying:(id)arg1 isForceStop:(_Bool)arg2;
- (void)OnSPXLevelMeter:(id)arg1 Peak:(float)arg2;
@end

