//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AudioReceiver.h"

#import "SilkAudioPlayerDelegate-Protocol.h"

@interface AudioReceiver (SilkAudioPlayerDelegate) <SilkAudioPlayerDelegate>
- (_Bool)onSilkEndDontNotifyOtherApp;
- (void)onSilkEarTip;
- (void)onSilkEndPlaying:(id)arg1 isForceStop:(_Bool)arg2;
- (void)onSilkBeginPlaying:(id)arg1 ErrNo:(int)arg2;
- (void)onSilkLevelMeter:(id)arg1 Peak:(float)arg2;
@end

