//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AudioSender.h"

#import "UploadVoiceDelegate-Protocol.h"

@interface AudioSender (UploadVoiceDelegate) <UploadVoiceDelegate>
- (void)OnPartSent:(id)arg1 ErrNo:(unsigned int)arg2;
@end

