//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AudioReceiver.h"

@interface AudioReceiver (InternalMethod)
- (_Bool)updateMessageToDB:(id)arg1;
- (_Bool)getMessageFromDB:(id)arg1;
- (id)getAudioFileName:(id)arg1 LocalID:(unsigned int)arg2;
- (id)getChatName:(id)arg1;
@end

