//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BCDEncoding : NSObject
{
}

+ (unsigned int)mycharTo4Bits:(unsigned char)arg1;
+ (id)dataFromHexString:(id)arg1;
+ (id)hexStringFromData:(id)arg1;

@end

