//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CContactMgr.h"

@interface CContactMgr (DB)
- (_Bool)SetFriendMetaFlag:(unsigned int)arg1 ForUser:(id)arg2;
- (_Bool)SetLastUpdateTime:(unsigned int)arg1 ForUser:(id)arg2;
- (_Bool)ModifyNotifyStatus:(id)arg1 withStatus:(unsigned int)arg2;
- (_Bool)thread_onPushModifyContact:(id)arg1 isInit:(_Bool)arg2;
- (_Bool)thread_BatchModifyContact:(id)arg1;
- (id)addOrUpdateContactToDB:(id)arg1 listType:(unsigned int)arg2 add:(_Bool *)arg3 modify:(_Bool *)arg4;
- (_Bool)getAllContactNoExtInfoList:(id)arg1 listType:(unsigned int)arg2;
- (_Bool)getAllContactList:(id)arg1 listType:(unsigned int)arg2;
- (_Bool)migrationContacts:(unsigned int)arg1 first:(_Bool)arg2;
- (void)reportMigrationStat:(unsigned int)arg1 status:(unsigned int)arg2;
- (_Bool)splist_migrationContactList:(id)arg1;
- (void)setMigrationFinished;
- (_Bool)loadContactExtInfo:(id)arg1;
- (_Bool)updateContactToDb:(id)arg1;
- (_Bool)addContactToDb:(id)arg1;
- (_Bool)removeContactFromDB:(id)arg1;
- (id)getContactFromDB:(id)arg1;
- (void)removeContactFromDic:(id)arg1;
- (void)setContactToDic:(id)arg1 forKey:(id)arg2;
- (id)getContactFromDic:(id)arg1;
@end

