//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "ChatMigrationRecoverChatFileHelperDelegate-Protocol.h"

@class BackupChatRecoverPacketInfo, ChatMigrationRecoverChatFileHelper, NSMutableDictionary, NSObject, NSString;
@protocol ChatMigrationRecoverChatLogicDelegate, OS_dispatch_queue;

@interface ChatMigrationRecoverChatLogic : MMObject <ChatMigrationRecoverChatFileHelperDelegate>
{
    ChatMigrationRecoverChatFileHelper *m_RecoverChatFileHelper;
    BackupChatRecoverPacketInfo *bakPackageInfo;
    NSObject<OS_dispatch_queue> *m_FileSerialQueue;
    unsigned int uiStoreFileWorkingCount;
    unsigned int m_totalFileWorkingCount;
    unsigned int m_totalMediaFileCount;
    NSMutableDictionary *m_dicBackupInfo;
    _Bool bIsRecovering;
    id <ChatMigrationRecoverChatLogicDelegate> m_delegate;
}

@property(nonatomic) __weak id <ChatMigrationRecoverChatLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onRecoverEnd:(id)arg1 isSuccess:(unsigned int)arg2;
- (void)onRecoverError:(int)arg1;
- (void)cancelRecover;
- (_Bool)startRecover;
- (void)asynProcessPieceOfData:(id)arg1;
- (void)processBackupDetailInfo:(id)arg1;
- (void)dealloc;
- (void)refreshRecoverChatLogicState;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

