//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class NSMutableArray, NSString;

@interface ClearDataMgr : MMService <MMService>
{
    NSMutableArray *_arrSessionInfo;
    unsigned long long _startLoadDataTime;
    unsigned int _loadDataCostTime;
    unsigned long long _fileSizeOver3Month;
    long long _nowTime;
    vector_91fc892d _arrSessionItems;
    vector_3d478e4e _arrDataItems;
    _Bool _loadingData;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)doCleanCache;
- (void)cleanCache;
- (void)innerDeleteDataItem:(struct ClearDataItem *)arg1;
- (void)doDeleteFilesOver3Month;
- (void)deleteFilesOver3Month;
- (unsigned long long)getFileSizeOver3Month;
- (void)deleteData:(const vector_3d478e4e *)arg1;
- (void)deleteSessionsAndKeepMessage:(const vector_91fc892d *)arg1;
- (void)deleteSessions:(const vector_91fc892d *)arg1;
- (const vector_91fc892d *)getAllSessionItem;
- (shared_ptr_174ad120)getSessionItemOfIndex:(unsigned long long)arg1;
- (unsigned long long)getCountOfSessionItem;
- (shared_ptr_88fac422)getDataItemOfIndex:(unsigned long long)arg1;
- (unsigned long long)getCountOfDataItem;
- (void)getDetailInfoForSessionInfo:(id)arg1;
- (void)onLoadData;
- (unsigned int)parseMesLocalIdFromPath:(id)arg1;
- (id)getSessionName:(id)arg1;
- (unsigned int)getLoadDataCostTime;
- (void)stopLoadData;
- (void)startLoadData;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

