//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMessageWrap.h"

#import "ISysNewXmlMsgExtendOperation-Protocol.h"

@class NSMutableArray, NSString;

@interface CMessageWrap (SysNewXml_ForBiz) <ISysNewXmlMsgExtendOperation>

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSMutableArray *m_arrMembers; // @dynamic m_arrMembers;
@property(retain, nonatomic) NSString *m_qrCode; // @dynamic m_qrCode;
@property(retain, nonatomic) NSString *m_scene; // @dynamic m_scene;
@property(retain, nonatomic) NSString *m_sessionShowContent; // @dynamic m_sessionShowContent;
@property(retain, nonatomic) NSString *m_showContent; // @dynamic m_showContent;
@property(retain, nonatomic) NSString *m_url; // @dynamic m_url;
@property(readonly) Class superclass;
@end

