//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMMDB.h"

@interface CMMDB (QQContact)
- (_Bool)DeleteQQContactByUserName:(id)arg1;
- (id)GetAllQQContactOnProperty:(const vector_24c76cbd *)arg1;
- (id)GetQQContactByUserName:(id)arg1 withProperty:(const vector_24c76cbd *)arg2;
@end

