//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMMDB.h"

@interface CMMDB (OpLog)
- (_Bool)DeleteOplog:(unsigned int)arg1;
- (id)GetOneOplogAfterOplogId:(unsigned int)arg1;
- (_Bool)InsertOplog:(id)arg1;
- (id)oplogDBDirWithDocDir:(id)arg1 userName:(id)arg2;
- (void)CloseOplogDB;
- (void)SetupOplogDBWithDocDir:(id)arg1 userName:(id)arg2;
@end

