//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMMDB.h"

@interface CMMDB (Contact)
- (_Bool)SetFriendMetaFlag:(unsigned int)arg1 ForUser:(id)arg2;
- (_Bool)SetLastUpdateTime:(unsigned int)arg1 ForUser:(id)arg2;
- (unsigned int)GetFriendMetaFlag:(id)arg1;
- (unsigned int)GetLastUpdateTimeOfUser:(id)arg1;
- (id)GetContactAndExtWithContactProperty:(const vector_24c76cbd *)arg1 contactExtProperty:(const vector_24c76cbd *)arg2 where:(const struct WCDBConditionBase *)arg3 getError:(id *)arg4 limit:(unsigned int)arg5;
- (unsigned int)getContactCount:(const struct WCDBConditionBase *)arg1;
- (id)ContactExtTableName;
- (id)ContactTableName;
- (_Bool)DeleteContactExtByUserName:(id)arg1;
- (id)GetContactExtByUserName:(id)arg1 property:(const vector_24c76cbd *)arg2;
- (_Bool)UpdateContactExt:(id)arg1 withProperty:(const vector_24c76cbd *)arg2 byUserName:(id)arg3;
- (_Bool)InsertContactExt:(id)arg1 withProperty:(const vector_24c76cbd *)arg2;
- (_Bool)IsContactExtExist:(id)arg1;
- (_Bool)IsContactExist:(id)arg1;
- (_Bool)DeleteContactByUserName:(id)arg1;
- (id)GetContactsWhere:(const struct WCDBConditionBase *)arg1 onProperty:(const vector_24c76cbd *)arg2 getError:(id *)arg3;
- (id)GetContactByUserName:(id)arg1 property:(const vector_24c76cbd *)arg2;
- (_Bool)UpdateExtentInContact:(id)arg1 byUserName:(id)arg2;
- (_Bool)UpdateContact:(id)arg1 withProperty:(const vector_24c76cbd *)arg2 byUserName:(id)arg3;
- (_Bool)InsertContact:(id)arg1 withProperty:(const vector_24c76cbd *)arg2;
@end

