//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMMDB.h"

@interface CMMDB (BottleDB)
- (_Bool)DeleteBottle:(unsigned int)arg1;
- (id)GetAllBottle:(const vector_24c76cbd *)arg1;
- (id)GetBottleByLocalID:(unsigned int)arg1 onProperty:(const vector_24c76cbd *)arg2;
- (unsigned int)GetServerIDInBottleByLocalID:(unsigned int)arg1;
- (unsigned int)GetLocalIDInBottleByBottleID:(id)arg1;
- (_Bool)UpdateBottle:(id)arg1 onProperty:(const vector_24c76cbd *)arg2 byLocalId:(unsigned int)arg3;
- (unsigned int)InsertBottle:(id)arg1 onProperty:(const vector_24c76cbd *)arg2;
@end

