//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCDataBaseEventDelegate-Protocol.h"

@class MMTimer, NSMutableSet, NSRecursiveLock, NSString, NewContactDB, OpLogDB, WCDataBase, WCDataBaseTable;

@interface CMMDB : NSObject <WCDataBaseEventDelegate>
{
    NSRecursiveLock *m_lockMMDB;
    NSMutableSet *m_setMessageCreatedTable;
    NSMutableSet *m_setMessageExtCreatedTable;
    OpLogDB *m_oplogWcdb;
    MMTimer *m_backupTimer;
    _Bool m_checkCorruption;
    WCDataBase *m_db;
    NewContactDB *m_contactDB;
    WCDataBaseTable *m_tableContact;
    WCDataBaseTable *m_tableContactExt;
    WCDataBaseTable *m_tableContactMeta;
    WCDataBaseTable *m_tableQQContact;
    WCDataBaseTable *m_tableSendMsg;
    WCDataBaseTable *m_tableUploadVoice;
    WCDataBaseTable *m_tableDownloadVoice;
    WCDataBaseTable *m_tableRevokeMsg;
    WCDataBaseTable *m_tableEmoticon;
    WCDataBaseTable *m_tableEmoticonUpload;
    WCDataBaseTable *m_tableEmoticonDownload;
    WCDataBaseTable *m_tableEmoticonPackage;
    WCDataBaseTable *m_tableBottle;
    WCDataBaseTable *m_tableBottleContact;
    WCDataBaseTable *m_tableMassSendContact;
}

+ (Class)getClassFromMessageTableName:(id)arg1;
+ (id)md5StringFromUserName:(id)arg1;
+ (id)helloMessageTableName:(id)arg1;
+ (id)messageExtTableName:(id)arg1;
+ (id)messageTableName:(id)arg1;
+ (id)dbPathWithDocDir:(id)arg1 userName:(id)arg2;
@property(retain, nonatomic) OpLogDB *m_oplogWcdb; // @synthesize m_oplogWcdb;
@property(retain) WCDataBaseTable *m_tableMassSendContact; // @synthesize m_tableMassSendContact;
@property(retain) WCDataBaseTable *m_tableBottleContact; // @synthesize m_tableBottleContact;
@property(retain) WCDataBaseTable *m_tableBottle; // @synthesize m_tableBottle;
@property(retain) WCDataBaseTable *m_tableEmoticonPackage; // @synthesize m_tableEmoticonPackage;
@property(retain) WCDataBaseTable *m_tableEmoticonDownload; // @synthesize m_tableEmoticonDownload;
@property(retain) WCDataBaseTable *m_tableEmoticonUpload; // @synthesize m_tableEmoticonUpload;
@property(retain) WCDataBaseTable *m_tableEmoticon; // @synthesize m_tableEmoticon;
@property(retain) WCDataBaseTable *m_tableRevokeMsg; // @synthesize m_tableRevokeMsg;
@property(retain) WCDataBaseTable *m_tableDownloadVoice; // @synthesize m_tableDownloadVoice;
@property(retain) WCDataBaseTable *m_tableUploadVoice; // @synthesize m_tableUploadVoice;
@property(retain) WCDataBaseTable *m_tableSendMsg; // @synthesize m_tableSendMsg;
@property(retain) WCDataBaseTable *m_tableQQContact; // @synthesize m_tableQQContact;
@property(retain) WCDataBaseTable *m_tableContactMeta; // @synthesize m_tableContactMeta;
@property(retain) WCDataBaseTable *m_tableContactExt; // @synthesize m_tableContactExt;
@property(retain) WCDataBaseTable *m_tableContact; // @synthesize m_tableContact;
@property(retain) NewContactDB *m_contactDB; // @synthesize m_contactDB;
@property(retain) WCDataBase *m_db; // @synthesize m_db;
- (void).cxx_destruct;
- (_Bool)onDatabaseCorrupt:(id)arg1 errorCode:(int)arg2 opType:(unsigned int)arg3;
- (void)endStatictics:(id)arg1 withColumn:(unsigned int)arg2;
- (id)beginStatictics:(unsigned int)arg1;
- (void)clearMessageExtCreatedTableCache;
- (void)removeMessageExtCreatedTableCache:(id)arg1;
- (void)addMessageExtCreatedTableCache:(id)arg1;
- (_Bool)isMessageExtTableCreated:(id)arg1;
- (void)clearMessageCreatedTableCache;
- (void)removeMessageCreatedTableCache:(id)arg1;
- (void)addMessageCreatedTableCache:(id)arg1;
- (_Bool)isMessageTableCreated:(id)arg1;
- (void)setupMessageCreatedTableCache;
- (id)GetHelloMessageTable:(id)arg1;
- (_Bool)CreateHelloMessageTable:(id)arg1;
- (void)ClearMessageAndExtCreatedTableCache;
- (void)DropMessageExtTable:(id)arg1;
- (id)GetMessageExtTable:(id)arg1;
- (_Bool)CreateMessageExtTable:(id)arg1;
- (void)DropMessageTable:(id)arg1;
- (id)GetMessageTable:(id)arg1;
- (_Bool)CreateMessageTable:(id)arg1;
- (void)setupEmiticonPackageTable;
- (void)setupTables;
- (id)internalCreateTable:(id)arg1 tableClass:(Class)arg2;
- (void)createOtherTable;
- (void)createBottleTable;
- (void)createEmoticonTable;
- (void)createMessagesTable;
- (void)createContactTable;
- (void)createTables;
- (void)clearTables;
- (void)closeDBBeforeInit;
- (void)onGenerateNewHandle:(struct sqlite3 *)arg1;
- (void)onTransactionRollback;
- (void)DropEmoticonDownloadTable;
- (_Bool)IsEmoticonPackageTableExist;
- (_Bool)CreateEmoticonPackageTable;
- (id)dbPaths;
- (id)dbPath;
- (id)DBContext;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1 stateDidChanged:(CDUnknownBlockType)arg2;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1;
- (void)CloseAndPreventOtherThreadsInBlock:(CDUnknownBlockType)arg1;
- (void)Close;
- (void)InitMMDB:(id)arg1 UsrName:(id)arg2 NewUser:(_Bool *)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

