//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol CommonPlayerDelegate;

@interface CommonPlayer : NSObject
{
    id <CommonPlayerDelegate> m_delegate;
}

@property(nonatomic) __weak id <CommonPlayerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (double)duration;
- (void)start;
- (void)resume;
- (void)pause;
- (void)stop;
- (void)updatePath:(id)arg1;

@end

