//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ContactsGenerator : NSObject
{
}

+ (id)GetRecentVoiceContact;
+ (id)GetRecentVideoContact;
+ (id)GetRecentConnectSingleContactWithMaxCount:(long long)arg1 CurrentContacts:(id)arg2;
+ (_Bool)IsNormalSingleContact:(id)arg1;
+ (id)getVOIPRecenetConnect;

@end

