//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CQQContactMgr.h"

@interface CQQContactMgr (Private)
- (void)initTestData;
- (void)initTestDataItem:(unsigned int)arg1 name:(id)arg2;
- (_Bool)onGetQQContact:(id)arg1 withImage:(_Bool)arg2;
- (_Bool)onSyncQQContact:(id)arg1;
- (void)internalDeleteContact:(id)arg1;
- (void)internalModifyContact:(id)arg1;
- (void)internalAddContact:(id)arg1;
- (void)removeListen;
- (void)initListen;
@end

