//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSMutableDictionary, NSString;

@protocol EmoticonWebDownloadMgrExt
- (void)onDownloadFailedWithUrl:(NSString *)arg1 userData:(NSMutableDictionary *)arg2 errType:(int)arg3;
- (void)onDownloadFinishedWithUrl:(NSString *)arg1 userData:(NSMutableDictionary *)arg2;
@end

