//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray;

@protocol EmoticonDownloadMd5ListCgiDelegate
- (void)onEmoticonDownloadMd5ListFailed;
- (void)onEmoticonDownloadMd5ListOk:(NSArray *)arg1;
@end

