//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IEnterpriseBrandContactMgrExt-Protocol.h"
#import "MMService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class EnterpriseBrandAttrDB, NSString;

@interface EnterpriseBrandAttrMgr : MMService <PBMessageObserverDelegate, MMService, IEnterpriseBrandContactMgrExt>
{
    EnterpriseBrandAttrDB *_db;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)handleGetBizEnterpriseAttrFromSvr:(id)arg1;
- (_Bool)updateAttrFromSvr:(id)arg1;
- (void)onEnterpriseBrandContactDeleted:(id)arg1;
- (void)onEnterpriseBrandContactChanged:(id)arg1;
- (unsigned int)getQyUinByUserName:(id)arg1;
- (id)getAttrByUserName:(id)arg1;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

