//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "EnterpriseSessionSearchControllerDelegate-Protocol.h"
#import "IEnterpriseGroupMgrExt-Protocol.h"
#import "IEnterpriseSessionMgrExt-Protocol.h"
#import "IMMNewSessionMgrExt-Protocol.h"
#import "MMWebViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CContact, EnterpriseSessionSearchController, MMSearchBar, MMTableView, MMTitleView, NSMutableArray, NSString, UIView;

@interface EnterpriseSessionListViewController : MMUIViewController <EnterpriseSessionSearchControllerDelegate, UITableViewDelegate, UITableViewDataSource, IEnterpriseSessionMgrExt, IEnterpriseGroupMgrExt, IMMNewSessionMgrExt, MMWebViewDelegate>
{
    unsigned int _scene;
    unsigned int _fromScene;
    MMTableView *_tableView;
    MMTitleView *_titleView;
    MMSearchBar *_searchBar;
    EnterpriseSessionSearchController *_searchController;
    UIView *_footerView;
    UIView *_footerViewBackground;
    UIView *_emptyView;
    NSMutableArray *_arySpecialSession;
    double preContentOffsetY;
    _Bool _isEntering;
    CContact *brandContact;
}

@property(retain, nonatomic) CContact *brandContact; // @synthesize brandContact;
- (void).cxx_destruct;
- (void)onWebViewWillClose:(id)arg1;
- (void)onSessionChanged:(id)arg1;
- (void)onSessionTotalUnreadCountChange:(unsigned int)arg1;
- (void)onCreateEnterpriseGroup:(id)arg1 errorCode:(int)arg2 extDic:(id)arg3;
- (void)onQuitEnterpriseGroup:(id)arg1 errorCode:(int)arg2;
- (void)onEnterpriseSessionChanged;
- (id)makeNormalCell:(id)arg1;
- (id)makeSpecialCell:(id)arg1;
- (_Bool)isSpecialIndex:(id)arg1;
- (id)brandCellDataWithMainUsrName:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)getViewController;
- (id)getMMSearchBar;
- (void)reloadTable;
- (void)enterChat:(id)arg1;
- (void)updateMemberToLocal:(id)arg1;
- (void)createChatroom:(id)arg1;
- (void)createSingleChat:(id)arg1;
- (void)openEnterpriseBrandSessionListView;
- (void)openFavSessionListView:(id)arg1;
- (void)openCreateChat:(id)arg1;
- (void)openChatBrandInfo:(id)arg1;
- (void)showRightTopMenuBtn:(id)arg1;
- (void)report;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillBePushed:(_Bool)arg1;
- (void)willDisappear;
- (void)willAppear;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)updateTitleView;
- (void)updateLeftBarItem;
- (void)initFooterView;
- (void)hideSearchBar;
- (void)initSearchBar;
- (void)initSpecialSession;
- (void)initData;
- (void)setScene:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithBrand:(id)arg1 fromScene:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

