//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface EnterpriseSpecialBrandSessionCellData : NSObject
{
    _Bool _showBadge;
    NSString *_textForTitleLabel;
    NSString *_headImageFileName;
}

@property(nonatomic) _Bool showBadge; // @synthesize showBadge=_showBadge;
@property(retain, nonatomic) NSString *headImageFileName; // @synthesize headImageFileName=_headImageFileName;
@property(retain, nonatomic) NSString *textForTitleLabel; // @synthesize textForTitleLabel=_textForTitleLabel;
- (void).cxx_destruct;

@end

