//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "EnterpriseBrandContactHelperDelegate-Protocol.h"
#import "EnterpriseBrandSearchControllerDelegate-Protocol.h"
#import "ForwardMessageLogicDelegate-Protocol.h"
#import "IEnterpriseBrandContactMgrExt-Protocol.h"
#import "IEnterpriseBrandSessionMgrExt-Protocol.h"
#import "IEnterpriseGroupMgrExt-Protocol.h"
#import "IMMNewSessionMgrExt-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class EnterpriseBrandContactHelper, EnterpriseBrandSearchController, ForwardMessageLogicController, MMSearchBar, MMTableView, NSMutableArray, NSString, UIView;

@interface EnterpriseBrandSessionListViewController : MMUIViewController <ForwardMessageLogicDelegate, EnterpriseBrandSearchControllerDelegate, WCActionSheetDelegate, IEnterpriseBrandContactMgrExt, EnterpriseBrandContactHelperDelegate, IEnterpriseBrandSessionMgrExt, UITableViewDelegate, UITableViewDataSource, IMMNewSessionMgrExt, IEnterpriseGroupMgrExt>
{
    NSString *_mainUserName;
    NSMutableArray *_arySpecialSession;
    MMTableView *_tableView;
    UIView *_footerView;
    UIView *_footerViewBackground;
    UIView *_emptyView;
    double preContentOffsetY;
    unsigned int _fromScene;
    EnterpriseBrandSearchController *_searchController;
    MMSearchBar *_searchBar;
    _Bool _isEntering;
    unsigned int _enterTime;
    EnterpriseBrandContactHelper *_helper;
    ForwardMessageLogicController *m_forwardLogic;
}

- (void).cxx_destruct;
- (id)getTitleString;
- (id)makeNormalCell:(id)arg1;
- (id)makeSpecialCell:(id)arg1;
- (_Bool)isSpecialIndex:(id)arg1;
- (id)chatCellDataWithMainUsrName:(id)arg1;
- (void)reloadTable;
- (void)openMainBrandInfo:(id)arg1;
- (void)openEnterpriseChat;
- (void)openDisabledBrandList:(id)arg1;
- (id)getCurrentViewController;
- (void)shareToFriend:(id)arg1;
- (void)openQRCode:(id)arg1;
- (void)showRightTopMenuBtn:(id)arg1;
- (id)getViewController;
- (id)getMMSearchBar;
- (void)onCreateEnterpriseGroup:(id)arg1 errorCode:(int)arg2 extDic:(id)arg3;
- (void)onEnterpriseBrandSessionsChanged:(id)arg1;
- (void)onSessionChanged:(id)arg1;
- (void)onSessionTotalUnreadCountChange:(unsigned int)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reportQuit;
- (void)reportEnter;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willDisappear;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)updateTitleView;
- (void)updateLeftBarItem;
- (void)hideSearchBar;
- (void)initSearchBar;
- (void)initFooterView;
- (void)initTableView;
- (void)initView;
- (void)initSpecialSession;
- (void)initData;
- (void)dealloc;
- (id)initWithEnterpriseMainUserName:(id)arg1 fromScene:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

