//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FishBottleLogicView.h"

#import "BottleTipViewDelegate-Protocol.h"

@interface FishBottleLogicView (BottleTipViewDelegate) <BottleTipViewDelegate>
- (void)BottleTipPressButton:(id)arg1 withButtonTitle:(id)arg2;
@end

