//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMessageNodeData;

@interface GameNode : NSObject
{
    CMessageNodeData *m_oNodeData;
    unsigned int m_uiAnimationTimes;
}

@property(nonatomic) unsigned int m_uiAnimationTimes; // @synthesize m_uiAnimationTimes;
@property(retain, nonatomic) CMessageNodeData *m_oNodeData; // @synthesize m_oNodeData;
- (void).cxx_destruct;
- (id)init;

@end

