//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GameCenterMsgCenterCellView, GameCenterMsgCenterContent, NSString;

@protocol GameCenterMsgCenterCellViewDelegate <NSObject>
- (void)onMergeUserImageClick:(GameCenterMsgCenterContent *)arg1 Url:(NSString *)arg2;
- (void)onUserHeadClick:(GameCenterMsgCenterContent *)arg1;
- (void)onUserNickNameClick:(GameCenterMsgCenterContent *)arg1;
- (void)onMediaContentClick:(GameCenterMsgCenterCellView *)arg1;
- (void)onSourceClick:(GameCenterMsgCenterCellView *)arg1;
@end

