//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

@class UIImageView;

@interface GameMessageNodeView : BaseMessageNodeView
{
    UIImageView *m_imageViewGame;
    unsigned int m_uiRealGameIndex;
    unsigned int m_uiGameType;
    unsigned int m_uiCurImageIndex;
    _Bool m_bIsSender;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)onMenuItemWillHide;
- (void)onTouchCancel;
- (void)onLongTouch;
- (void)onTouchUpInside;
- (void)onTouchDownRepeat;
- (void)onTouchDown;
- (void)showOperations;
- (void)onMoreOperate:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onClearResource;
- (void)onDisappear;
- (void)updateStatus:(id)arg1;
- (void)layoutSubviewsInternal;
- (void)stopAnimation;
- (void)doAnimation;
- (id)getGameImageByIndex:(unsigned int)arg1;
- (void)chageGameImage:(id)arg1;
- (id)tryGenHQImage:(id)arg1;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;

@end

