//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMTimer, NSMutableArray;

@interface GameController : NSObject
{
    NSMutableArray *m_arrNodeData;
    MMTimer *m_timer;
}

+ (id)getMD5ByGameContent:(unsigned int)arg1;
@property(retain, nonatomic) MMTimer *m_timer; // @synthesize m_timer;
- (void).cxx_destruct;
- (void)Reset;
- (void)sendGameMessage:(id)arg1 toUsr:(id)arg2;
- (void)addNodeData:(id)arg1;
- (void)doAnimation;
- (void)stopTimer;
- (void)startTimer;
- (void)dealloc;
- (id)init;

@end

