//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CaptureVideoInfo, ImageInfo, MMAsset, NSData, UIImage, UIViewController;

@protocol ImageControllerDelegate <NSObject>
- (_Bool)CanSendVideoMsg;
- (_Bool)CanSendMultiImage;
- (_Bool)CanSendOriginalImage;
- (UIViewController *)getViewController;

@optional
- (void)processImageControllerDidCancel:(unsigned long long)arg1;
- (void)CameraControllerDidTakeVideo:(CaptureVideoInfo *)arg1;
- (void)processImageDidFinish;
- (void)processImageDidCancel;
- (void)processInsertedImage:(UIImage *)arg1 withData:(NSData *)arg2 ImageInfo:(ImageInfo *)arg3;
- (void)processInsertedImage:(UIImage *)arg1 ImageInfo:(ImageInfo *)arg2;
- (void)processInsertedAsset:(MMAsset *)arg1;
@end

