//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol IWCOutCallExt <NSObject>

@optional
- (void)OnCheckNumberResp:(unsigned int)arg1 RespCountryCode:(NSString *)arg2;
- (void)didReceiveInviteGap:(int)arg1;
- (void)OnCallEndFinish;
- (void)OnUpdateCallStateWithText:(NSString *)arg1 hasBeAccepted:(_Bool)arg2 isCallEnded:(_Bool)arg3 isError:(_Bool)arg4 errorlevel:(unsigned long long)arg5 ErrTitle:(NSString *)arg6 showChargeAlert:(_Bool)arg7;
@end

