//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol IWebviewResourceManagerExt <NSObject>

@optional
- (void)onResourceDownloadFinished:(NSString *)arg1 SvrId:(NSString *)arg2 ErrCode:(int)arg3;
- (void)onResourceDownloadProgress:(int)arg1 SvrId:(NSString *)arg2;
- (void)onLocalResourceUploadFinishedWithoutMediaId:(NSString *)arg1 FileUrl:(NSString *)arg2 ErrCode:(int)arg3;
- (void)onLocalResourceUploadProgressWithouMediaId:(int)arg1 LocalId:(NSString *)arg2;
- (void)onLocalResourceUploadFinished:(NSString *)arg1 SvrId:(NSString *)arg2 ErrCode:(int)arg3;
- (void)onLocalResourceUploadProgress:(int)arg1 LocalId:(NSString *)arg2;
- (void)onLocalImageSaveFinish:(NSArray *)arg1;
@end

