//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PrtlBase.h"

@class LbsContactInfoList;

@interface LBSFindPrtl : PrtlBase
{
    float fLongitude;
    float fLatitude;
    int iPrecision;
    int iOpCode;
    LbsContactInfoList *m_lbsContactList;
}

@property(retain, nonatomic) LbsContactInfoList *lbsContactList; // @synthesize lbsContactList=m_lbsContactList;
@property(nonatomic) int iOpCode; // @synthesize iOpCode;
@property(nonatomic) int iPrecision; // @synthesize iPrecision;
@property(nonatomic) float fLatitude; // @synthesize fLatitude;
@property(nonatomic) float fLongitude; // @synthesize fLongitude;
- (void).cxx_destruct;
- (_Bool)HandleResp:(void *)arg1;
- (void)InitReq:(void *)arg1;
- (id)init;

@end

