//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NetCmdEvent.h"

@interface LBSFindEvent : NetCmdEvent
{
    float fLongitude;
    float fLatitude;
    int iPrecision;
    int iOpCode;
}

@property(nonatomic) int iOpCode; // @synthesize iOpCode;
@property(nonatomic) int iPrecision; // @synthesize iPrecision;
@property(nonatomic) float fLatitude; // @synthesize fLatitude;
@property(nonatomic) float fLongitude; // @synthesize fLongitude;
- (void)NotifyFromPrtl:(unsigned int)arg1 MessageInfo:(id)arg2;
- (_Bool)Start:(unsigned int *)arg1 RetInfo:(id)arg2;
- (_Bool)SetEventInfo:(id)arg1;
- (void)dealloc;
- (id)init;

@end

