//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString;

@protocol MailContentViewDelegate
- (void)contentLengthChanged:(NSString *)arg1;
- (void)contentViewDidFinishEdit;
- (void)contentViewNeedSetContentOffset:(double)arg1;
- (void)didStartWriteMailContent;
@end

