//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MessageNodeComponentHelper : NSObject
{
}

+ (id)getWCPayInfoView:(id)arg1 maxWidth:(double)arg2;
+ (double)getSourceViewHeight;
+ (id)getSourceViewWithTitle:(id)arg1 iconName:(id)arg2 maxWidth:(double)arg3;
+ (id)getSourceViewWithTitle:(id)arg1 iconImage:(id)arg2 maxWidth:(double)arg3 withBkgImg:(_Bool)arg4;
+ (id)getMaskCoverImage:(_Bool)arg1;
+ (id)getImageBorderImage:(_Bool)arg1;
+ (id)getBackgroundImage:(_Bool)arg1;
+ (double)getSystemTextFontSize;

@end

