//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMConfigMgr.h"

@interface MMConfigMgr (Security)
- (unsigned int)getHeightLimitForShowingTextMsg;
- (unsigned int)getInputLimitFileSize;
- (unsigned int)getInputLimitVideoSize;
- (unsigned int)getInputLimitFavVoiceLength;
- (unsigned int)getInputLimitFavImageSize;
- (unsigned int)getInputLimitEmotionWidth;
- (unsigned int)getInputLimitEmotionBufSize;
- (unsigned int)getInputLimitForFavMsg;
- (unsigned int)getInputLimitForFloatBottleMsg;
- (unsigned int)getInputLimitForTextMsg;
@end

