//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMDBRestore-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class NSString;

@interface MMDBRestoreManualViewController : MMUIViewController <MMDBRestore, WCActionSheetDelegate, UIAlertViewDelegate>
{
}

- (void)onRestoreProgressUpdate:(float)arg1;
- (void)safeUpdateProgress:(float)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onClear;
- (void)onRestore;
- (void)alertWithMsg:(id)arg1 btn:(id)arg2;
- (void)alertWithRestoreResult:(_Bool)arg1 error:(id)arg2;
- (void)initView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

