//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface MMDumpReportData : NSObject
{
    NSMutableArray *m_uploadFilesArray;
    unsigned long long m_reportType;
}

@property(nonatomic) unsigned long long m_reportType; // @synthesize m_reportType;
@property(retain, nonatomic) NSMutableArray *m_uploadFilesArray; // @synthesize m_uploadFilesArray;
- (void).cxx_destruct;

@end

