//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class NSMutableArray, NSString;

@interface MMEasterEggMgr : MMService <MMService>
{
    _Bool m_isShowEgg;
    unsigned int m_uiEasterEggLastUpdateTime;
    NSMutableArray *m_arrEgg;
}

- (void).cxx_destruct;
- (id)eggWithMessage:(id)arg1 isSender:(_Bool)arg2;
- (_Bool)isShowEasterEgg;
- (void)dealloc;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

