//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMEasterEggMgr.h"

#import "MMPackageDownloadMgrExt-Protocol.h"

@interface MMEasterEggMgr (MMPackageDownloadMgrExt) <MMPackageDownloadMgrExt>
- (void)onPackageNeedDelete:(id)arg1 withPackIDs:(id)arg2;
- (void)onPackageNeedUpdate:(id)arg1 withPackIDs:(id)arg2;
- (void)onPackageListUpdated:(id)arg1;
@end

