//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IClearDataMgrExt-Protocol.h"
#import "MMService-Protocol.h"

@class MMFreeSpaceCheckConfig, MMTimer, NSString;

@interface MMFreeSpaceCheckMgr : MMService <MMService, IClearDataMgrExt>
{
    MMFreeSpaceCheckConfig *m_config;
    MMTimer *m_checkFreeSpaceTimer;
    unsigned long long _urgentFreeSpaceSize;
    unsigned long long _lowFreeSpaceSize;
}

+ (id)testFilePath;
+ (id)configPath;
+ (id)workDir;
- (void).cxx_destruct;
- (void)onCleanedCacheSize:(unsigned long long)arg1;
- (_Bool)getFreeSize:(unsigned long long *)arg1;
- (_Bool)isLowSpace:(unsigned long long)arg1;
- (_Bool)isUrgentSpace:(unsigned long long)arg1;
- (void)renewAlertLowSpaceTime;
- (void)renewAlertUrgentSpaceTime;
- (void)saveConfig;
- (void)loadConfig;
- (void)createWorkDir;
- (void)alertLowSpaceAfterClearData;
- (void)alertLowSpace;
- (void)alertUrgentSpace;
- (void)calFreeSpace;
- (void)setup;
- (void)checkAfterClearData;
- (void)CheckFreeSpace;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

