//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMHttpConnection.h"

@interface MMHttpConnection (InternalMethods)
- (_Bool)connectWithRequest:(id)arg1;
- (_Bool)setPostRequestHeader:(id)arg1 boundary:(id)arg2;
- (_Bool)setNormalRequestHeader:(id)arg1;
@end

