//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMIconActionSheet, MMIconActionSheetCell;

@protocol MMIconActionSheetDelegate <NSObject>

@optional
- (void)actionSheet:(MMIconActionSheet *)arg1 didDismissWithItem:(MMIconActionSheetCell *)arg2;
- (void)actionSheet:(MMIconActionSheet *)arg1 willDismissWithItem:(MMIconActionSheetCell *)arg2;
- (void)actionSheetCancel:(MMIconActionSheet *)arg1;
- (void)actionSheet:(MMIconActionSheet *)arg1 didSelectWithItem:(MMIconActionSheetCell *)arg2;
@end

