//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMImageUtil.h"

@interface MMImageUtil (MaskImage)
+ (id)maskedFourRoundedCornerImageForColor:(id)arg1 imageSize:(struct CGSize)arg2;
+ (id)maskedTwoRoundedCornerImageForColor:(id)arg1 imageSize:(struct CGSize)arg2;
+ (id)getImageByColor:(id)arg1 inSize:(struct CGSize)arg2 isSender:(_Bool)arg3;
+ (id)maskAlbumBkgImage:(id)arg1 isSender:(_Bool)arg2 inSize:(struct CGSize)arg3;
+ (id)maskImage:(id)arg1 isSender:(_Bool)arg2 inSize:(struct CGSize)arg3;
+ (void)addReceiverNodeAlbumBkgPathToContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2 scale:(double)arg3;
+ (void)addSenderNodeAlbumBkgPathToContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2 scale:(double)arg3;
+ (void)addReceiverNodeViewPathToContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2 scale:(double)arg3;
+ (void)addSenderNodeViewPathToContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2 scale:(double)arg3;
@end

