//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMImageUtil.h"

@interface MMImageUtil (ThumbImage)
+ (id)hdImageWithContentsOfFile:(id)arg1;
+ (id)maskedThumbImageForVideoMessageImage:(id)arg1 imageSize:(struct CGSize)arg2 isSender:(_Bool)arg3;
+ (id)maskedThumbImageForMessageImage:(id)arg1 imageSize:(struct CGSize)arg2 isSender:(_Bool)arg3;
+ (struct CGSize)maskedVideoThumbImageSizeForMessageImage:(struct CGSize)arg1;
+ (struct CGSize)maskedThumbImageSizeForMessageImage:(struct CGSize)arg1;
+ (struct CGSize)maskedVideoThumbImageSize:(struct CGSize)arg1;
+ (struct CGSize)maskedThumbImageSize:(struct CGSize)arg1;
@end

