//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMPickerViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MMPickerView, MMTableView, NSArray, NSMutableDictionary, NSString;

@interface MMKVLogDebugViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, MMPickerViewDelegate>
{
    MMTableView *_tableView;
    NSMutableDictionary *_kvLogDic;
    NSArray *_selectedKvList;
    NSString *_selectedLogId;
    MMPickerView *m_pickerView;
    unsigned long long _fromScene;
}

- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)genShowLabel:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)sortedAllKey;
- (void)MMPickerViewDidChooseRow:(long long)arg1 atSession:(long long)arg2;
- (id)convertLogid2IdKey:(id)arg1;
- (void)onClickSelectLogId:(id)arg1;
- (void)onClickClear:(id)arg1;
- (void)onClickRefresh:(id)arg1;
- (id)genTableHeaderView;
- (void)initView;
- (void)initData;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithFromScene:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

