//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WCDataBase, WCDataBaseTable;

@interface MMLocationDB : NSObject
{
    WCDataBase *m_db;
    WCDataBaseTable *m_table;
}

@property(retain, nonatomic) WCDataBaseTable *m_table; // @synthesize m_table;
@property(retain, nonatomic) WCDataBase *m_db; // @synthesize m_db;
- (void).cxx_destruct;
- (_Bool)setAddress:(id)arg1 ByLocation:(CDStruct_c3b9c2ee)arg2;
- (id)getAddressByLocation:(CDStruct_c3b9c2ee)arg1;
- (void)closeDBBeforeInit;
- (void)closeDB;
- (void)setupDatabase;
- (id)pathForDatabase;
- (id)init;

@end

