//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol MMPatchMgrExt <NSObject>

@optional
- (void)onPatchCodeUpdateFail:(unsigned int)arg1 errorCode:(long long)arg2;
- (void)onPatchCodeUpdateSuccess:(unsigned int)arg1;
@end

