//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMVoiceSearchBar.h"

@interface MMVoiceSearchBar (InternalMethods)
- (void)onVideoVoipViewDisappear;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (_Bool)setVoiceSearchStatusFrom:(int)arg1 transferToStatus:(int)arg2;
- (_Bool)setVoiceSearchStatusFrom:(int)arg1 transferToStatus:(int)arg2 withVoiceID:(int)arg3;
- (_Bool)canFromStatus:(int)arg1 transferToStatus:(int)arg2;
- (void)loadView;
- (void)setVoiceSearchBarFrame:(_Bool)arg1 animation:(_Bool)arg2;
- (void)setVoiceSearchToParentView:(id)arg1;
@end

