//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewController.h"

@interface MMWebViewController (LogFeatureOrIDKeyReport)
- (void)reportIDKeyForLoadFinish:(long long)arg1;
- (void)reportIDKeyForSystemError:(long long)arg1;
- (void)reportIDKeyForAllRequest;
- (void)logFeature11576WithOpType:(unsigned int)arg1;
@end

