//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class MMTimer, MMWebViewController, NSMutableArray, NSMutableDictionary, NSString;

@interface MMWebViewKeepHolderMgr : MMService <MMService>
{
    MMWebViewController *_webViewVCForNewMainFrameBanner;
    NSMutableArray *_dpArrOpenedWebview;
    NSMutableDictionary *_dicBackgroundWebviewTask;
    NSMutableArray *_arrTaskOrder;
    MMTimer *_checkTimer;
    _Bool _bIsDelayLoading;
}

- (void).cxx_destruct;
- (_Bool)onServiceMemoryWarning;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

