//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewController.h"

#import "WCForceTouchPopProtocol-Protocol.h"

@class NSString, UIView, UIViewController;

@interface MMWebViewController (ForceTouch) <WCForceTouchPopProtocol>
- (void)log3DTouchWebViewActionFeatureWithOpType:(id)arg1;
- (id)previewActionItems;
- (id)initForPreviewWithURL:(id)arg1 presentModal:(_Bool)arg2 extraInfo:(id)arg3;
- (void)commitViewController;
- (_Bool)canPop;
@property(nonatomic) __weak UIView *previewSourceView;
@property(nonatomic) __weak UIViewController *previewFromController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

