//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewKeepHolderMgr.h"

@interface MMWebViewKeepHolderMgr (background_multitask)
- (void)onCheckBackgroundTaskTimeOut;
- (void)cleanAllBackgroundTask;
- (id)getCurrentAllPresentingBackgroundVC;
- (void)deleteBackgroundTaskForKey:(id)arg1;
- (id)getBackgroundTaskForKey:(id)arg1;
- (_Bool)addBackgroundTask:(id)arg1 forKey:(id)arg2 IsPresented:(_Bool)arg3;
@end

