//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewKeepHolderMgr.h"

@interface MMWebViewKeepHolderMgr (jsapi_dispatchEvent)
- (void)dp_sendJSEventToAllWebView:(id)arg1 Param:(id)arg2 AppID:(id)arg3 Host:(id)arg4;
- (void)dp_deleteWebView:(id)arg1;
- (void)dp_addWebViewAsWeak:(id)arg1;
@end

