//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class MMDelegateProxy, MultiTalkSessionItem, NSArray;
@protocol MultiTalkSessionDetailLogicControllerDelegate;

@interface MultiTalkSessionDetailLogicController : MMObject
{
    MMDelegateProxy<MultiTalkSessionDetailLogicControllerDelegate> *_delegate;
    MultiTalkSessionItem *_sessionItem;
    NSArray *_sessionMemberArray;
    NSArray *_sessionMesssageArray;
}

@property(retain, nonatomic) NSArray *sessionMesssageArray; // @synthesize sessionMesssageArray=_sessionMesssageArray;
@property(retain, nonatomic) NSArray *sessionMemberArray; // @synthesize sessionMemberArray=_sessionMemberArray;
@property(retain, nonatomic) MultiTalkSessionItem *sessionItem; // @synthesize sessionItem=_sessionItem;
@property(nonatomic) __weak MMDelegateProxy<MultiTalkSessionDetailLogicControllerDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleStartMultiTalk;
- (id)getSessionMessageList;
- (id)getSessionMemberList;
- (long long)numberOfMemberListCount;
- (long long)numberOfMessageListCount;
- (void)initData;
- (id)initWithSessionItem:(id)arg1;
- (void)dealloc;

@end

