//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "MMovieDecoderDelegate-Protocol.h"

@class MMovieDecoder, NSString, UIImage;
@protocol MVideoPlayerViewDelegate;

@interface MVideoPlayerView : UIImageView <MMovieDecoderDelegate>
{
    MMovieDecoder *m_decoder;
    UIImage *m_firstFrame;
    UIImage *m_lastFrame;
    id <MVideoPlayerViewDelegate> delegate;
    NSString *_cpKey;
}

@property(retain, nonatomic) NSString *cpKey; // @synthesize cpKey=_cpKey;
@property(retain, nonatomic) UIImage *lastFrame; // @synthesize lastFrame=m_lastFrame;
@property(nonatomic) __weak id <MVideoPlayerViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)mMovieDecoder:(id)arg1 onNewVideoFrameReady:(struct opaqueCMSampleBuffer *)arg2;
- (void)mMovieDecoderOnDecodeFinished:(id)arg1;
- (void)restart;
- (void)pauseForRelease;
- (void)pause;
- (void)loadAndPlay:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

