//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyFavoritesDB.h"

@interface MyFavoritesDB (FavoritesDownloadCdnInfoDB)
- (_Bool)deleteDownloadCdnInfoByFavoritesItemLocalId:(unsigned int)arg1;
- (_Bool)updateDownloadCdnInfo:(id)arg1 byItemLocalDataId:(id)arg2 andType:(int)arg3;
- (id)getDownloadCdnInfoByLocalItemDataId:(id)arg1 andType:(int)arg2;
- (id)getNextDownloadCdnInfoByLocalItemId:(unsigned int)arg1;
- (_Bool)insertNewRowInDownloadCdnInfoTable:(id)arg1;
@end

