//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MyFavoritesDB.h"

@interface MyFavoritesDB (FavoritesSearchDB)
- (id)getSearchItemListByType:(int)arg1 SearchContent:(id)arg2;
- (_Bool)deleteSearchItemByLocalFavId:(unsigned int)arg1;
- (_Bool)insertOrUpdateFavSearchItem:(id)arg1;
@end

