//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NewQRCodeScanner;

@protocol NewQRCodeScannerDelegate <NSObject>

@optional
- (void)onGotBarcode:(NSString *)arg1 Type:(NSString *)arg2;
- (void)NewQRCodeScanner:(NewQRCodeScanner *)arg1 didScanResult:(NSString *)arg2 type:(NSString *)arg3 version:(int)arg4;
@end

