//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableSet.h>

@interface NSMutableSet (Swizzle)
+ (void)swizzleRemoveObject:(Class)arg1;
+ (void)swizzleAddObject:(Class)arg1;
+ (void)load;
- (void)mmRemoveObject:(id)arg1;
- (void)mmAddObject:(id)arg1;
@end

