//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString, PBCContact, PBCMessageWrap;

@interface PBSessionInfo : NSObject <PBCoding>
{
    _Bool showUnreadCountAsRedDot;
    unsigned int atMeCount;
    unsigned int greenLabelType;
    PBCContact *contact;
    PBCMessageWrap *message;
}

+ (void)initialize;
@property(nonatomic) unsigned int greenLabelType; // @synthesize greenLabelType;
@property(nonatomic) _Bool showUnreadCountAsRedDot; // @synthesize showUnreadCountAsRedDot;
@property(nonatomic) unsigned int atMeCount; // @synthesize atMeCount;
@property(retain, nonatomic) PBCMessageWrap *message; // @synthesize message;
@property(retain, nonatomic) PBCContact *contact; // @synthesize contact;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

