//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PreEnterWechatLogic.h"

@interface PreEnterWechatLogic (CheckShowRating)
- (void)onForFeedbackYes;
- (void)onForFeedbackNo;
- (void)onFirstAskNo;
- (void)onFirstAskYes;
- (void)onFirstAskForRatingNo;
- (void)onFirstAskForRatingYes;
- (void)onRatingReport:(unsigned int)arg1;
- (void)onShowRatingDone;
- (void)checkShowRating;
- (void)cleanSetting;
@end

