//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PSTNMgr.h"

@interface PSTNMgr (Talk)
- (void)TalkBroken:(id)arg1;
- (void)StopTalk;
- (void)StartAudioData;
- (void)StartAudioDataInNewThread;
- (void)StartRecordAndPlayAudioForVoip;
- (void)StartTalk;
- (void)tryStartTalk;
@end

