//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PSTNSyncMgr.h"

#import "PBMessageObserverDelegate-Protocol.h"

@interface PSTNSyncMgr (RecvResponse) <PBMessageObserverDelegate>
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)HandlePSTNSyncResp:(id)arg1 Event:(unsigned int)arg2;
- (void)check_next_sync;
@end

