//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QCommonTool : NSObject
{
}

+ (_Bool)isZeroForCoordinate:(CDStruct_c3b9c2ee)arg1;
+ (CDStruct_90e2a262)minixumMapRectForMapPoints:(CDStruct_c3b9c2ee *)arg1 count:(unsigned long long)arg2;

@end

