//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol QCoord <NSObject>
+ (id)coord;
- (double)QMaxPoint;
- (CDStruct_c3b9c2ee)QCoordinateForMapPoint:(CDStruct_c3b9c2ee)arg1;
- (CDStruct_c3b9c2ee)QMapPointForCoordinate:(CDStruct_c3b9c2ee)arg1;
@end

