//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString;

@protocol QDataCacheProtocol <NSObject>
@property(copy, nonatomic) NSString *version;
- (void)clearCache;
- (NSData *)cacheDataWithTile:(CDStruct_2ec95fd7)arg1;
- (_Bool)writeCacheData:(NSData *)arg1 tile:(CDStruct_2ec95fd7)arg2 version:(NSString *)arg3;
@end

