//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString, NSURL, UIImage;

@protocol QDataSourceProtocol <NSObject>
@property(readonly, nonatomic) double tileSize;
- (NSData *)tileData:(CDStruct_2ec95fd7)arg1;

@optional
@property(readonly, nonatomic) unsigned long long mapLanguage;
@property(readonly, nonatomic) long long maxZoomLevel;
@property(readonly, nonatomic) long long minZoomLevel;
- (UIImage *)tileImage:(CDStruct_2ec95fd7)arg1;
- (NSURL *)tileURL:(CDStruct_2ec95fd7)arg1;
- (NSString *)tilePath:(CDStruct_2ec95fd7)arg1;
@end

