//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QMapView.h"

@interface QMapView (NotifyDelegate)
- (void)completeRegionChangeEventByZoom:(_Bool)arg1 animated:(_Bool)arg2;
- (void)registerRegionChangeEventByZoom:(_Bool)arg1 animated:(_Bool)arg2;
- (void)notifyDelegateRegionDidChangeAnimated:(_Bool)arg1;
- (void)notifyDelegateRegionWillChangeAnimated:(_Bool)arg1;
- (void)notifyDelegateDidFailLoadingWithError:(id)arg1;
@end

