//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface QQEmojiDataHelper : MMObject
{
}

+ (void)initEmojiCodes;
+ (id)getEmojiCode:(id)arg1;
+ (id)getEmojiString:(id)arg1;
+ (id)getSymbolString:(id)arg1;
+ (id)getQQEmoticonString:(id)arg1;
+ (id)getDeleteKey;
+ (_Bool)isDeleteKey:(id)arg1;
+ (id)getQQPid;
+ (id)getQQemojiPageWrap;
+ (id)getQQEmojiArrayByCountPerPage:(long long)arg1;
+ (_Bool)isEmojiString:(id)arg1;
+ (_Bool)isQQEmoticonString:(id)arg1;
+ (id)getFinalCode:(id)arg1;
+ (id)getFinalString:(id)arg1;
+ (id)getQQEmoticonImage:(id)arg1;

@end

