//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QQMailMgr.h"

#import "IMsgExt-Protocol.h"

@interface QQMailMgr (MailCache) <IMsgExt>
- (void)OnDelMsg:(id)arg1 DelAll:(_Bool)arg2;
- (void)OnDelMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)DeleteMailByMailId:(id)arg1;
- (void)SaveMail:(id)arg1 byMailId:(id)arg2;
- (void)LoadMail:(id *)arg1 byMailId:(id)arg2;
@end

