//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle;

@interface QResourceReader : NSObject
{
    NSBundle *_bundle;
}

+ (id)instance;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
- (void).cxx_destruct;
- (id)init;
- (void)setupBundle;
- (id)imageNamed:(id)arg1;
- (id)userLocationImage;
- (id)googleLogoImage;
- (id)tencentLogoImage;
- (id)embeddedImageNamed:(id)arg1;
- (id)userlocation;
- (id)userlocation2x;
- (id)googleMapLogo;
- (id)googleMapLogo2x;
- (id)tencentMapLogo;
- (id)tencentMapLogo2x;

@end

