//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QAnnotation-Protocol.h"

@class NSString;

@interface QShape : NSObject <QAnnotation>
{
    NSString *_title;
    NSString *_subtitle;
    NSString *title;
    NSString *subtitle;
    CDStruct_2c43369c coordinate;
}

@property(readonly, nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate;
@property(copy) NSString *subtitle; // @synthesize subtitle;
@property(copy) NSString *title; // @synthesize title;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

