//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface RemoteControlActionReport : MMObject
{
}

+ (void)ReportPrevTrack;
+ (void)ReportNextTrack;
+ (void)ReportStop;
+ (void)ReportPause;
+ (void)ReportPlay;
+ (void)ReportFinishRecordForWXTalk;
+ (void)ReportBeginRecordForWXTalk;
+ (void)ReportFinishRecordForChat;
+ (void)ReportBeginRecordForChat;
+ (void)reportDataForAction:(unsigned int)arg1 scene:(unsigned int)arg2;

@end

