//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SandyBeachViewController.h"

@interface SandyBeachViewController (InternalUIMethods)
- (void)undoSandyAnimation:(_Bool)arg1;
- (void)doSandyAnimation;
- (void)showWarningTipViewNoConfirm:(id)arg1;
- (void)showWarningTipView:(id)arg1;
- (void)updateBottleCountLabel;
- (void)updateFishCountLabel;
- (void)updateThrowCountLabel;
- (void)removeViewSlipToLeft:(_Bool)arg1;
- (void)addViewSlipToLeft:(_Bool)arg1;
- (void)hideTopBar;
- (void)initButtonView;
- (id)cropImage:(id)arg1 toFitSize:(struct CGSize)arg2;
- (void)viewDidTransitionToNewSize;
- (void)initBgView;
@end

