//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewControllerDelegate-Protocol.h"

@class CContact, NSArray, NSString, SessionSelectView;

@protocol SessionSelectViewDelegate <MMUIViewControllerDelegate>
- (void)OnSelectSession:(CContact *)arg1 SelectView:(SessionSelectView *)arg2;

@optional
- (void)selectViewWillBeginDragging:(SessionSelectView *)arg1;
- (void)OnSelectFromContactSelectView:(SessionSelectView *)arg1;
- (void)OnSelectEnterpriseChat:(CContact *)arg1 SelectView:(SessionSelectView *)arg2;
- (void)OnSelectCreateRoomSelectView:(SessionSelectView *)arg1;
- (NSString *)onSessionSelectGetSearchString;
- (void)onSessionSelectSearch:(NSArray *)arg1;
- (_Bool)OnShouldSelectSession:(CContact *)arg1 SelectView:(SessionSelectView *)arg2;
@end

