//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "IMsgExt-Protocol.h"
#import "IMsgRevokeExt-Protocol.h"
#import "IVOIPUILogicMgrExt-Protocol.h"
#import "IVideoExt-Protocol.h"
#import "IWXVideoPlayerViewExt-Protocol.h"
#import "SightIconViewDelegate-Protocol.h"
#import "SightPlayerViewDelegate-Protocol.h"
#import "SightViewDelegate-Protocol.h"

@class NSString, SightView, UIImageView;

@interface ShortVideoMessageNodeView : BaseMessageNodeView <IVOIPUILogicMgrExt, IWXVideoPlayerViewExt, SightViewDelegate, IMsgRevokeExt, IVideoExt, IMsgExt, SightPlayerViewDelegate, SightIconViewDelegate>
{
    UIImageView *m_thumbImg;
    SightView *_playerView;
    struct CGRect m_vedioFrame;
    _Bool m_isLoading;
    _Bool m_isClickDownload;
    unsigned long long _sightLegalityType;
    _Bool _mayBeIllegalAD;
    _Bool _isVideoExpired;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)checkLegalityWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)canAutoPlaySettingFromServer;
- (_Bool)isInFlowControl;
- (_Bool)shouldAutoDownload;
- (_Bool)shouldAutoPlay;
- (void)onWXVideoPlayerViewPlay:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (id)getMessageDisplayView;
- (void)clearShortVideo;
- (void)stopPlayShortVideo;
- (void)playShortVideo;
- (void)onResumeSightView:(id)arg1;
- (void)onStackSightView:(id)arg1;
- (_Bool)sightView:(id)arg1 playbackDidReadEnd:(_Bool)arg2;
- (void)sightViewProgressDidReachEnd:(id)arg1;
- (void)setThumbImage:(id)arg1;
- (_Bool)generateThumbImage;
- (_Bool)isSightVideoPlayable;
- (void)handleDownloadFail;
- (void)setProgress:(unsigned int)arg1;
- (void)UpdateVideoMsg:(id)arg1;
- (void)OnUpdateVideoStatus:(id)arg1 MsgWrap:(id)arg2;
- (void)OnThumbDownloadFailed:(id)arg1;
- (void)OnThumbDownloadOK:(id)arg1;
- (void)onProgressEnd;
- (void)OnVideoGetIntoUploadQueue:(id)arg1;
- (id)thumbImage;
- (void)onClick;
- (void)onTouchUpInside;
- (id)makeSenderMaskLayer;
- (id)makeRecieverMaskLayer;
- (id)makeRecieverPath:(double)arg1;
- (id)makeSenderPath:(double)arg1;
- (void)OnMsgDownloadVideoExpiredFail:(id)arg1 MsgWrap:(id)arg2;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)onAppear;
- (void)showOpearation;
- (void)onMoreOperate:(id)arg1;
- (void)onFavoriteAdd:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (_Bool)isSendFailed;
- (void)layoutSubviewsInternal;
- (void)reLayoutSubviews;
- (void)layoutSubviews;
- (struct CGSize)videoSizeForThumbSize:(struct CGSize)arg1;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)dealloc;
- (void)commonInit;
- (id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

