//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSObject;
@protocol SightQRCodeScannerDelegate;

@protocol SightPreviewView
- (void)setQRFrameEnable:(_Bool)arg1;
- (_Bool)supportQRFrame;
- (void)forceFocusAnimAtPoint:(struct CGPoint)arg1;
- (void)startFocusAnimAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)transformPointInView:(struct CGPoint)arg1;

@optional
- (void)setReady;
- (_Bool)isReady;
- (void)setQRScannerDelegate:(NSObject<SightQRCodeScannerDelegate> *)arg1;
@end

