//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IVOIPUILogicMgrExt-Protocol.h"
#import "InputControllerDelegate-Protocol.h"
#import "MultiSelectContactsViewControllerDelegate-Protocol.h"
#import "SightMomentGroupSelectDelegate-Protocol.h"
#import "SightViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCGroupTagViewControllerDelegate-Protocol.h"
#import "WCTimelinePOIPickerViewControllerDelegate-Protocol.h"

@class EmoticonBoardView, MMGrowTextView, NSArray, NSMutableArray, NSString, SightView, UIImage, UIImageView, UILabel, UIView, WCInputController, WCLocationInfo, WCTimelinePOIPickerViewController;

@interface SightMomentEditViewController : MMUIViewController <InputControllerDelegate, SightMomentGroupSelectDelegate, MultiSelectContactsViewControllerDelegate, IVOIPUILogicMgrExt, SightViewDelegate, WCTimelinePOIPickerViewControllerDelegate, WCActionSheetDelegate, WCGroupTagViewControllerDelegate>
{
    UIView *m_content;
    UIView *m_background;
    UIImageView *m_blurView;
    MMGrowTextView *_textView;
    EmoticonBoardView *m_emoticonBoardView;
    WCInputController *m_inputController;
    UIView *m_previewContent;
    SightView *_sightView;
    UIView *m_fullPlayContent;
    UILabel *m_fullPlayLabel;
    _Bool m_isFullPlaying;
    UIView *m_toolBar;
    double m_curToolBarY;
    WCTimelinePOIPickerViewController *m_poiPickerViewController;
    _Bool _directClose;
    _Bool _fromDraft;
    double _originHeight;
    UIImage *_thumbImage;
    NSString *_moviePath;
    UIImage *_realThumbImage;
    NSString *_realMoviePath;
    NSString *_realThumbPath;
    NSMutableArray *_arr_MentionContact;
    WCLocationInfo *_m_locationInfo;
    NSArray *_tempSelectContacts;
}

@property(retain, nonatomic) NSArray *tempSelectContacts; // @synthesize tempSelectContacts=_tempSelectContacts;
@property(retain, nonatomic) WCLocationInfo *m_locationInfo; // @synthesize m_locationInfo=_m_locationInfo;
@property(retain, nonatomic) NSMutableArray *arr_MentionContact; // @synthesize arr_MentionContact=_arr_MentionContact;
@property(retain, nonatomic) NSString *realThumbPath; // @synthesize realThumbPath=_realThumbPath;
@property(retain, nonatomic) NSString *realMoviePath; // @synthesize realMoviePath=_realMoviePath;
@property(retain, nonatomic) UIImage *realThumbImage; // @synthesize realThumbImage=_realThumbImage;
@property(retain, nonatomic) NSString *moviePath; // @synthesize moviePath=_moviePath;
@property(retain, nonatomic) UIImage *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(nonatomic) _Bool fromDraft; // @synthesize fromDraft=_fromDraft;
@property(nonatomic) _Bool directClose; // @synthesize directClose=_directClose;
@property(nonatomic) double originHeight; // @synthesize originHeight=_originHeight;
- (void).cxx_destruct;
- (void)GroupTagViewControllerWillDissappear;
- (void)GroupTagViewSelectTempContacts:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (_Bool)sightView:(id)arg1 playbackDidReadEnd:(_Bool)arg2;
- (void)privatePrivacyHiddenMentionBtn;
- (void)updateMentionBtn;
- (void)onMultiSelectContactCancelForSns;
- (void)onMultiSelectContactReturnForSns:(id)arg1;
- (void)onMultiSelectContactReturn:(id)arg1;
- (void)saveDraftAndQuit;
- (void)startSentAnim:(struct CGRect)arg1;
- (_Bool)isFromWCListView;
- (void)processUploadTask:(id)arg1;
- (void)uploadMoment;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onOtherBtn:(id)arg1;
- (void)keyboardWillShow;
- (void)keyboardWillHide;
- (void)MMGrowTextViewHeightDidChanged:(id)arg1;
- (double)getVisibleHeight;
- (id)getGroupDesc;
- (void)updateGroupBtn;
- (void)onSelectGroupFinish;
- (void)showGroupSelection;
- (void)switchEmojiPanel;
- (void)showMutiSelectContactViewController;
- (void)mentionContactSelect;
- (void)onPOIPickerFinished:(id)arg1;
- (void)poiSelect;
- (void)resignInput;
- (void)onServiceEnterForeground:(id)arg1;
- (void)onServiceEnterBackground:(id)arg1;
- (void)removeObservers;
- (void)addObservers;
- (void)makeInputController;
- (void)makeEmoticonView;
- (void)makeToolBar;
- (void)makeEditArea;
- (void)endFullPlay;
- (void)fullPlay;
- (void)makeFullPlayView;
- (void)makePreviewPlayer;
- (void)makePreviewContent;
- (void)makeTopBar;
- (void)makeBackground;
- (void)popSelf;
- (_Bool)shouldEnableKeyboardInteractivePop;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)fixKeyboardTextColorForIOS8;
- (_Bool)shouldInteractivePop;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillBeDismissed:(_Bool)arg1;
- (void)willAppearanceTransition;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

