//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMTimer;

@interface SightRecordProgressBar : UIView
{
    double m_currState;
    double m_animStep;
    MMTimer *m_timer;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateAnimation;
- (void)stopProgress;
- (void)runProgress:(double)arg1;
- (void)reflash;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

