//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class DelayInfo, Preload, QuestionBar, SocialInfluenceInfo;

@interface SnsOperations : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) QuestionBar *bar; // @dynamic bar;
@property(retain, nonatomic) DelayInfo *delayinfo; // @dynamic delayinfo;
@property(retain, nonatomic) Preload *preload; // @dynamic preload;
@property(nonatomic) unsigned int snsOperationsFlag; // @dynamic snsOperationsFlag;
@property(retain, nonatomic) SocialInfluenceInfo *socialInfluenceInfo; // @dynamic socialInfluenceInfo;

@end

