//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWindowViewController.h"

@class InteractionLabel, NSString, UIButton, UIImageView, UILabel;
@protocol SvrErrorTipViewControllerDelegate;

@interface SvrErrorTipViewController : MMWindowViewController
{
    UIImageView *_deviceView;
    UILabel *_tipsLabel;
    InteractionLabel *_descriptionLabel;
    UIButton *_cancelBtn;
    NSString *_errTip;
    id <SvrErrorTipViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SvrErrorTipViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewDidLayoutSubviews;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)onTopBarFrameChanged;
- (void)setupInfoView;
- (void)updateErrTip:(id)arg1;
- (void)hideView;
- (void)onDetailBtnClicked;
- (void)onCancelBtnClicked;
- (void)setupLineView;
- (void)setupCancelBtn;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

