//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (ModalView)
- (void)DismissMyselfAnimated:(_Bool)arg1;
- (void)DismissModalViewControllerAnimated:(_Bool)arg1;
- (void)PresentModalViewController:(id)arg1 animated:(_Bool)arg2;
@end

