//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ReaderNewMessageNodeView.h"

@class AsyncImageView, UIImageView, UILabel, UIView;

@interface VideoReaderMessageNodeView : ReaderNewMessageNodeView
{
    UIView *_containerView;
    AsyncImageView *_coverImageView;
    UIImageView *_coverImageBottomMaskView;
    UIImageView *_coverImageIconView;
    UILabel *_coverImageTimeLabel;
    UILabel *_titleLabel;
    _Bool _isTitleMultiRow;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)titleText;
- (id)timeText;
- (id)coverImageURL;
- (void)updateBkgImage:(_Bool)arg1;
- (_Bool)isTitleLabelMultiRow;
- (unsigned long long)titleLabelFontSize;
- (unsigned long long)titleLabelWidth;
- (id)titleLabel:(unsigned long long)arg1;
- (void)layoutTitleView;
- (void)layoutCoverImageView;
- (void)initTitleView;
- (void)initCoverImageView;
- (void)reLayoutSubviews;
- (void)layoutForSubview;
- (void)initView;
- (unsigned long long)messageNodeViewBottomMargin;
- (unsigned long long)messageNodeViewHeight:(_Bool)arg1;
- (unsigned long long)messageNodeViewWidth;
- (void)layoutSubviewsInternal;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;

@end

