//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, VoiceRecogView;
@protocol NSObject, VoiceInputViewDelegate;

@interface VoiceInputView : UIView
{
    unsigned int mVoiceId;
    id <NSObject> keyboard_targetor;
    SEL keyboard_selector;
    id <NSObject> send_targetor;
    SEL send_selector;
    int voiceInputStatus;
    id <VoiceInputViewDelegate> delegate;
    VoiceRecogView *mRecogView;
    UIButton *mKeyboardBtn;
    UIButton *mSendBtn;
}

@property(retain, nonatomic) UIButton *mSendBtn; // @synthesize mSendBtn;
@property(retain, nonatomic) UIButton *mKeyboardBtn; // @synthesize mKeyboardBtn;
@property(retain, nonatomic) VoiceRecogView *mRecogView; // @synthesize mRecogView;
@property(nonatomic) id <VoiceInputViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)stopVoiceInput;
- (void)resetView;
- (void)addSendTarget:(id)arg1 action:(SEL)arg2;
- (void)addKeyboardTarget:(id)arg1 action:(SEL)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)OnSendBtnClicked:(id)arg1;
- (void)OnClearBtnClicked:(id)arg1;
- (void)stopRecord;
- (void)startRecord;
- (void)changeBkgView;

@end

