//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "IAudioReceiverExt-Protocol.h"

@class UIButton;

@interface VoiceReminderRemindNodeView : BaseMessageNodeView <IAudioReceiverExt>
{
    UIButton *_playButton;
    long long _playCount;
    _Bool _playing;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)getMoreMainInfomationAccessibilityDescription;
- (void)onMenuItemWillHide;
- (void)onTouchCancel;
- (void)onLongTouch;
- (void)onTouchUpInside;
- (void)onTouchDownRepeat;
- (void)onTouchDown;
- (void)onClearResource;
- (void)onDisappear;
- (void)layoutSubviewsInternal;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)OnEndPlaying:(unsigned int)arg1 isForceStop:(_Bool)arg2;
- (id)init;
- (void)initData;
- (void)updateBkgImage:(_Bool)arg1;
- (void)initView;
- (void)dealloc;
- (void)onPlayClick;
- (void)stopPlayVoice;
- (void)startPlayVoice;

@end

