//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VOIPMgr.h"

@interface VOIPMgr (Data)
- (int)OnTransportChannelRttAndLR:(unsigned int)arg1 lostRate:(unsigned int)arg2 type:(unsigned int)arg3;
- (int)OnTransportChannelData:(int)arg1 pData:(void *)arg2 len:(int)arg3;
- (void)GetRtcpInfoS2P:(struct T_RtcpInfoS2P *)arg1:(char *)arg2:(int)arg3;
- (void)GetRtcpInfoP2S:(struct T_RtcpInfoP2S *)arg1:(char *)arg2:(int)arg3;
- (void)DataNotify_pp:(char *)arg1 len:(int)arg2 param:(short)arg3;
- (void)DataNotify_Arq:(char *)arg1 len:(int)arg2 type:(unsigned char)arg3;
- (void)DataNotify:(char *)arg1 len:(int)arg2;
- (_Bool)SetRtcpInfoP2S:(id)arg1:(struct T_RtcpInfoP2S *)arg2;
- (void)HandleS2PPkt:(id)arg1;
- (void)BuildP2SLinkInfo:(id)arg1;
- (void)EventNotify:(long long)arg1 param:(int)arg2 type:(int)arg3;
- (void)RenderTexture:(struct __CVBuffer *)arg1;
- (float)getVideoDegreesWithOrientation:(long long)arg1;
- (long long)calOrientationWithNotify:(int)arg1;
@end

