//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VOIPCSMgr.h"

@interface VOIPCSMgr (Stat)
- (void)SetCSReportData:(id *)arg1 voipCS3rdReport:(id *)arg2 channelReport:(id *)arg3 engineReport:(id *)arg4;
@end

