//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VOIPMgr.h"

#import "AVVideoDataSource-Protocol.h"

@class NSString;

@interface VOIPMgr (AVVideoDataSource) <AVVideoDataSource>
- (int)VideoDevPutData:(int)arg1 frmData:(char *)arg2 imageWidth:(unsigned int)arg3 imageHeight:(unsigned int)arg4;
- (int)ReInitHWEnc;
- (void)UpdateHWQosParam;
- (void)UpdateHWDecSession;
- (void)SetHWEncBR:(int)arg1;
- (int)GetHWEncWidth;
- (int)GetFrmType;
- (int)DecFrmError;
- (void)SendCloseHWEncCmd:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

