//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class MMTimer, NSData, NSMutableArray, NSRecursiveLock, NSString;

@interface VOIPCSSyncMgr : MMService <MMService>
{
    _Bool mIsWeakSessionActive;
    _Bool mIsSessionActive;
    _Bool mIsNeedSync;
    long long mRoomId;
    long long mRoomKey;
    _Bool m_isDoingSync;
    int cancelInviteStatus;
    unsigned int mCSNotifySeq;
    unsigned int m_syncTimerCnt;
    unsigned int m_syncTimerStopValue;
    NSData *mKeyBuf;
    NSMutableArray *mOplogList;
    NSRecursiveLock *mOplogLock;
    MMTimer *m_syncTimer;
}

@property(nonatomic) unsigned int m_syncTimerStopValue; // @synthesize m_syncTimerStopValue;
@property(nonatomic) unsigned int m_syncTimerCnt; // @synthesize m_syncTimerCnt;
@property(retain, nonatomic) MMTimer *m_syncTimer; // @synthesize m_syncTimer;
@property(retain, nonatomic) NSRecursiveLock *mOplogLock; // @synthesize mOplogLock;
@property(retain, nonatomic) NSMutableArray *mOplogList; // @synthesize mOplogList;
@property(retain, nonatomic) NSData *mKeyBuf; // @synthesize mKeyBuf;
- (void).cxx_destruct;
- (void)StopSession;
- (void)PushRelayData:(id)arg1;
- (void)PushControlStatus:(unsigned int)arg1;
- (void)SyncByNotifyWithRoomId:(long long)arg1 andRoomKey:(long long)arg2;
- (void)StartSessionWithRoomId:(long long)arg1 andRoomKey:(long long)arg2;
- (void)StartWeakSessionWithRoomId:(long long)arg1 andRoomKey:(long long)arg2;
- (void)forceCheck_next_sync;
- (void)StartSyncTimer:(unsigned long long)arg1;
- (void)StopSyncTimer;
- (void)dealloc;
- (id)init;
- (int)getSitemStatus;
- (long long)getRoomKey;
- (long long)getRoomId;
- (void)onServiceReloadData;
- (void)onServiceClearData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

