//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIWindow.h"

@protocol VoipAlertViewDelegate;

@interface VoipAlertView : MMUIWindow
{
    int _inviteType;
    id <VoipAlertViewDelegate> _mydelegate;
}

@property(nonatomic) id <VoipAlertViewDelegate> delegate; // @synthesize delegate=_mydelegate;
- (void)onInvite;
- (void)onCancel;
- (void)appearWithAnimation;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1 andInviteType:(int)arg2;

@end

