//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VOIPCSMgr.h"

@interface VOIPCSMgr (Engine)
- (void)StopCSEngine;
- (void)StartCSEngine;
- (void)SetMVEInfo:(CDStruct_33d8b17a *)arg1;
- (int)GetHWEncWidth;
- (void)SendCloseHWEncCmd:(int)arg1;
- (int)ReInitHWEnc;
- (void)StartVideoData;
- (void)StartRecordAndPlayAudioForVoip;
- (void)StartAudioDataInNewThread;
- (void)StartAudioData;
@end

