//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VOIPModeSwitchMgr.h"

@interface VOIPModeSwitchMgr (InternalMethods)
- (void)CallBackForModeStatus:(int)arg1;
- (void)SetAudioSpeakerPhone:(_Bool)arg1;
- (void)PushControlStatusToRemote:(unsigned int)arg1;
@end

