//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "IWCCardPkgExt-Protocol.h"
#import "WCCardListViewControllerDelegate-Protocol.h"
#import "WCNewCardDetailViewControllerDelegate-Protocol.h"

@class MMUIViewController, NSMutableArray, NSString;
@protocol WCBatchViewCardHelpDelegate;

@interface WCBatchViewCardHelper : MMObject <IWCCardPkgExt, WCNewCardDetailViewControllerDelegate, WCCardListViewControllerDelegate>
{
    NSString *_templateMsgId;
    NSMutableArray *_aryCardData;
    MMUIViewController *_currViewController;
    id <WCBatchViewCardHelpDelegate> _delegate;
}

@property(nonatomic) __weak id <WCBatchViewCardHelpDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MMUIViewController *currViewController; // @synthesize currViewController=_currViewController;
@property(retain, nonatomic) NSMutableArray *aryCardData; // @synthesize aryCardData=_aryCardData;
@property(retain, nonatomic) NSString *templateMsgId; // @synthesize templateMsgId=_templateMsgId;
- (void).cxx_destruct;
- (void)onGetCardsItemByTpInfo:(id)arg1 ErrCode:(int)arg2;
- (void)onUseCard:(id)arg1 lastIndex:(id)arg2 delayTime:(double)arg3;
- (void)onGiftCard:(id)arg1 lastIndex:(id)arg2;
- (void)onWCCardDetailViewControllerCancel:(id)arg1;
- (void)onWCCardListViewControllerDidSelected:(id)arg1 listViewController:(id)arg2;
- (void)onWCCardListViewControllerCancel:(id)arg1;
- (void)handleCardTpInfoList:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

