//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCBeaconLogReporter.h"

@interface WCBeaconLogReporter (GuideMode)
+ (void)reportBeaconCgiResultInScene:(unsigned long long)arg1 withBeacons:(id)arg2 location:(id)arg3 errorType:(unsigned long long)arg4 errorCode:(int)arg5;
+ (void)reportRedDotType:(unsigned long long)arg1 actionType:(unsigned long long)arg2 ForOwner:(unsigned long long)arg3;
@end

