//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WCCardBatchImportViewControllerDelegate-Protocol.h"
#import "WCNewCardDetailViewControllerDelegate-Protocol.h"

@class NSString;
@protocol WCCardAddHelperDelegate;

@interface WCCardAddHelper : MMObject <WCNewCardDetailViewControllerDelegate, WCCardBatchImportViewControllerDelegate>
{
    id <WCCardAddHelperDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)onShareFail:(id)arg1;
- (void)onShareSuccess:(id)arg1;
- (void)onCancel;
- (void)onImportFail:(id)arg1;
- (void)onImportSuccess:(id)arg1;
- (void)onAcceptCardCancel;
- (void)onAcceptCardFail:(id)arg1;
- (void)onAcceptCardSuccess:(id)arg1;
- (void)dismissViewController;
- (void)cancelHandle;
- (void)handleCardListInfo:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

