//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCUploader.h"

@class WCUploadTask;
@protocol WCDataUploaderDelegate;

@interface WCDataUploader : WCUploader
{
    long long currentPos;
    int uploadResult;
    int uploadErrType;
    WCUploadTask *m_task;
    id <WCDataUploaderDelegate> m_delegate;
}

@property(nonatomic) __weak id <WCDataUploaderDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) WCUploadTask *m_task; // @synthesize m_task;
- (void).cxx_destruct;
- (void)onResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)setFinished;
- (_Bool)onSetRequest:(id)arg1;
- (id)xmlForUploadTask:(id)arg1;

@end

