//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCDataBase.h"

@interface WCDataBase (Backup)
+ (id)backupPathsFrom:(id)arg1;
- (id)backupPaths;
- (void)clearBackup;
- (_Bool)backup;
- (id)getRestoreInfos;
- (id)accquireRestoreInfos;
- (id)accquireSortedBackupInfos;
@end

