//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCDataBase.h"

@interface WCDataBase (NoARC)
- (_Bool)noARC_bindProperty:(id)arg1 toSTMT:(struct sqlite3_stmt *)arg2 forItem:(id)arg3 atIndex:(int)arg4;
- (void)noARC_extractOneObject:(id)arg1 fromItem:(id)arg2 index:(int)arg3 STMT:(struct sqlite3_stmt *)arg4;
- (id)noARC_extractOneObjectRepeatedOfClass:(Class)arg1 withColumnInfo:(id *)arg2 STMT:(struct sqlite3_stmt *)arg3;
- (id)noARC_extractOneObjectOfClass:(Class)arg1 fromSTMT:(struct sqlite3_stmt *)arg2;
@end

