//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSThread;
@protocol WCDBHandleWrapProtocol;

@interface WCDBHandleWrap : NSObject
{
    NSThread *m_usedThread;
    struct sqlite3 *m_handle;
    id <WCDBHandleWrapProtocol> m_delegate;
    unsigned int m_waitTimes;
    unsigned int m_waitInterval;
    NSError *_error;
}

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)dealloc;
- (void)addWaitInterval:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int waitInterval;
@property(readonly, nonatomic) unsigned int waitTimes;
@property(readonly, nonatomic) __weak NSThread *usedThread;
@property(readonly, nonatomic) struct sqlite3 *handle;
- (id)initWithHandle:(struct sqlite3 *)arg1 andDelegate:(id)arg2;

@end

