//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFacade.h"

@interface WCFacade (LocalLogic_Delete)
- (void)LLDelete_onAfterDeleteDataItemFinished:(id)arg1;
- (void)LLDelete_onBeforeDeleteDataItem:(id)arg1;
- (void)notifyTotalCountWhenDataItemDeleted:(id)arg1;
@end

