//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFacade.h"

@interface WCFacade (FeedExposureReport)
- (unsigned int)getMaxCacheLogCount;
- (unsigned int)getMaxCacheTime;
- (_Bool)needUploadData;
- (void)exposurStatExitTimeLine;
- (void)reportData;
- (void)tryReportData;
- (void)recordFeedExposureWithFeedId:(id)arg1;
- (_Bool)hadExposuredWithFeedId:(id)arg1;
- (id)getExposureFeedIdDic;
- (_Bool)saveExposureFeedIdDic;
- (id)pathForExposureDicCache;
@end

