//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UISlider.h>

@class UIColor;

@interface WCNetworkMediaSlider : UISlider
{
    double m_cacheTime;
    UIColor *_frontgroundColor;
    UIColor *_backgroundColor;
}

@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *frontgroundColor; // @synthesize frontgroundColor=_frontgroundColor;
- (void).cxx_destruct;
- (id)getFrontgroundImage;
- (id)getBackgroundImage;
- (void)setCacheProgress:(double)arg1;
- (void)initView;

@end

