//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactsSelectorControllerDelegate-Protocol.h"
#import "IFacebookAuthExt-Protocol.h"
#import "IMMAssetICloudExt-Protocol.h"
#import "IMMFacebookMgrExt-Protocol.h"
#import "IMMGrowTextViewExt-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "MMTableViewInfoDelegate-Protocol.h"
#import "MMTwitterAuthExt-Protocol.h"
#import "SelectorControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"
#import "WCFacadeExt-Protocol.h"
#import "WCGroupTagViewControllerDelegate-Protocol.h"
#import "WCTimelinePOIPickerViewControllerDelegate-Protocol.h"
#import "scrollViewDelegate-Protocol.h"

@class CLLocation, ContactsSelectorController, EmoticonBoardView, ImageSelectorController, MMGrowTextView, MMLoadingView, MMTableViewInfo, MMTimer, NSArray, NSString, UIButton, UIImageView, UIView, WCDataItem, WCInputController, WCLocationInfo, WCMusicInfo, WCSelectorView, WCTimelinePOIPickerViewController;
@protocol WCCommitViewAnimationDelegate;

@interface WCNewCommitViewController : MMUIViewController <IMMAssetICloudExt, WCGroupTagViewControllerDelegate, UIScrollViewDelegate, scrollViewDelegate, UITextViewDelegate, SelectorControllerDelegate, MMTableViewInfoDelegate, ContactsSelectorControllerDelegate, UIAlertViewDelegate, IMsgExt, WCFacadeExt, MMTwitterAuthExt, IMMFacebookMgrExt, IFacebookAuthExt, IMMGrowTextViewExt, WCTimelinePOIPickerViewControllerDelegate>
{
    MMTableViewInfo *_tableViewInfo;
    MMGrowTextView *_textView;
    UIView *_headView;
    WCSelectorView *_withImageView;
    WCSelectorView *_withContactView;
    UIButton *_qzoneButton;
    UIButton *_facebookButton;
    UIButton *_twitterButton;
    ImageSelectorController *_imageSelectorController;
    ContactsSelectorController *_contactsSelectorController;
    WCInputController *_inputController;
    _Bool _bHasInput;
    UIImageView *_inputView;
    UIButton *_expressionButton;
    unsigned int _iInputSection;
    id <WCCommitViewAnimationDelegate> _delegate;
    WCDataItem *_cacheDateItem;
    MMLoadingView *_loadingView;
    MMTimer *_fireTimer;
    WCLocationInfo *_poiInfo;
    WCMusicInfo *_musicInfo;
    _Bool _bNeedRefresh;
    _Bool _bNeedAnimation;
    _Bool _bShowLocation;
    _Bool _bHideAddView;
    unsigned long long _singlePasteTextMaxLength;
    WCTimelinePOIPickerViewController *_poiPickerViewController;
    NSString *_loadingOKStr;
    _Bool m_hasClickDone;
    _Bool bCommmitOnlyText;
    _Bool m_isUseMMAsset;
    _Bool m_hasConfirmReturn;
    _Bool m_hasICloudImage;
    _Bool m_bFromWCList;
    EmoticonBoardView *m_emoticonBoardView;
    CLLocation *m_imageLocation;
    NSArray *_tempSelectContacts;
}

@property(retain, nonatomic) NSArray *tempSelectContacts; // @synthesize tempSelectContacts=_tempSelectContacts;
@property(nonatomic) _Bool bHideAddView; // @synthesize bHideAddView=_bHideAddView;
@property(nonatomic) _Bool m_bFromWCList; // @synthesize m_bFromWCList;
@property(retain, nonatomic) CLLocation *m_imageLocation; // @synthesize m_imageLocation;
@property(nonatomic) _Bool m_hasICloudImage; // @synthesize m_hasICloudImage;
@property(nonatomic) _Bool m_hasConfirmReturn; // @synthesize m_hasConfirmReturn;
@property(retain, nonatomic) EmoticonBoardView *m_emoticonBoardView; // @synthesize m_emoticonBoardView;
@property(nonatomic) _Bool m_isUseMMAsset; // @synthesize m_isUseMMAsset;
@property(retain, nonatomic) NSString *loadingOKStr; // @synthesize loadingOKStr=_loadingOKStr;
@property(nonatomic) _Bool bCommmitOnlyText; // @synthesize bCommmitOnlyText;
@property(retain, nonatomic) WCMusicInfo *musicInfo; // @synthesize musicInfo=_musicInfo;
@property(retain, nonatomic) WCLocationInfo *poiInfo; // @synthesize poiInfo=_poiInfo;
@property(nonatomic) _Bool bShowLocation; // @synthesize bShowLocation=_bShowLocation;
@property(nonatomic) _Bool bNeedAnimation; // @synthesize bNeedAnimation=_bNeedAnimation;
@property(nonatomic) __weak id <WCCommitViewAnimationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)onPOIPickerFinished:(id)arg1;
- (_Bool)couldSelectContacts;
- (void)hideInputController;
- (_Bool)showAddView;
- (void)updateSelectorView;
- (_Bool)shouldJustReturnMMAsset;
- (void)imagesUpdated;
- (void)onWCPostPrivacyChanged;
- (void)facebookCheckAccessTokenValidFinished:(_Bool)arg1;
- (void)fbDidNotLogin;
- (void)fbDidLogin;
- (void)twitterCheckAccessTokenValidFinished:(int)arg1;
- (void)twitterAuthFinished:(int)arg1;
- (void)twitterWillStartOpenSafari;
- (void)adjustSubviewRects;
- (void)updateImageLocation:(unsigned int *)arg1;
- (void)OnDone;
- (void)OnPostTimeline;
- (_Bool)checkImageState;
- (void)afterProcessSingleImage;
- (_Bool)processImage;
- (void)cancelIcloudActivity;
- (void)doExit;
- (void)OnReturn;
- (void)OnFacebookBinded;
- (void)onTwitterClicked:(id)arg1;
- (void)onFacebookClicked:(id)arg1;
- (void)onLocationCellClicked;
- (void)onWithContactCellClicked;
- (void)onPrivacyCellClicked;
- (void)onQZoneClicked:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)bindFacebook;
- (void)bindQQ;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)showPrivacyAlertView;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)shareOptionsCheck;
- (void)initView;
- (void)reloadData;
- (id)getShowAddress;
- (void)createSubviews;
- (void)saveShareOptions;
- (void)restoreLastShareOptions;
- (void)removeOldText;
- (void)writeOldText:(id)arg1;
- (id)openOldText;
- (id)getViewController;
- (id)initWithImages:(id)arg1 contacts:(id)arg2;
- (id)init;
- (void)commonInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

