//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CBaseContact, NSString;

@protocol WCNetworkMediaPlayerDelegate <NSObject>
- (void)onClosePlayer;

@optional
- (_Bool)needHiddenMoreMenu;
- (void)onShareVideoToTimeline:(_Bool)arg1;
- (void)onCancelShareVideoToFriend;
- (void)onShareVideoToFriend:(CBaseContact *)arg1;
- (void)onClickFavVideoMenu;
- (void)willAnimateRotation:(_Bool)arg1;
- (void)onClosePlayerForViewDetail:(NSString *)arg1;
- (_Bool)stopAtLastVideoFrameWhenPlayEnd;
- (void)onEndPlayer;
- (void)onPausePlayer;
- (void)onStartPlayer;
@end

