//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCOpLog : NSObject
{
}

- (_Bool)modSnsBlackList:(id)arg1 modType:(long long)arg2 syncNow:(_Bool)arg3;
- (_Bool)changeStrangerRight:(_Bool)arg1 sync:(_Bool)arg2;
- (id)init;

@end

