//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayLogicMgr.h"

@interface WCPayLogicMgr (Balance)
- (void)SetIsShowedBalanceFirstTips:(_Bool)arg1;
- (_Bool)IsShowedBalanceFirstTips;
- (id)getLocalBalanceInfo;
- (_Bool)updateBalanceWithInfo:(id)arg1 partical:(_Bool)arg2;
@end

