//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class UIImageView, WCPayControlData;

@interface WCPayAvaliableFavorView : MMUIView
{
    WCPayControlData *m_data;
    struct CGRect m_frame;
    UIImageView *m_backgroundView;
}

- (void).cxx_destruct;
- (_Bool)shouldPreventedAutorotateToInterfaceOrientation;
- (void)closeView;
- (void)showAnimation;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 Data:(id)arg2;

@end

