//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString, WCSnsDelayShowInfo, WCSnsPreLoadInfo, WCSnsSocialInfluenceInfo;

@interface WCSnsOperation : MMObject <PBCoding>
{
    WCSnsSocialInfluenceInfo *socialInfluenceInfo;
    WCSnsPreLoadInfo *preloadInfo;
    WCSnsDelayShowInfo *delayShowInfo;
}

+ (void)initialize;
@property(retain, nonatomic) WCSnsDelayShowInfo *delayShowInfo; // @synthesize delayShowInfo;
@property(retain, nonatomic) WCSnsPreLoadInfo *preloadInfo; // @synthesize preloadInfo;
@property(retain, nonatomic) WCSnsSocialInfluenceInfo *socialInfluenceInfo; // @synthesize socialInfluenceInfo;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

