//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@protocol WCTimelineTipViewDelegate;

@interface WCTimelineTipView : MMUIView
{
    id <WCTimelineTipViewDelegate> _delegate;
    _Bool _showTipNow;
    _Bool _closeTipNow;
    _Bool _hidingTip;
}

+ (id)showTipWithDelegate:(id)arg1 parentView:(id)arg2 content:(id)arg3;
@property(nonatomic) _Bool showTipNow; // @synthesize showTipNow=_showTipNow;
@property(nonatomic) __weak id <WCTimelineTipViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showTipView:(double)arg1 withAnimationTimes:(id)arg2 AnimationValues:(id)arg3;
- (void)closeTipView:(_Bool)arg1;
- (void)showTipView:(_Bool)arg1;
- (void)hideTipView:(_Bool)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (id)getAnimationLayer;
- (void)performBgAction;
- (void)initView;
- (id)init;

@end

