//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class WCDataItem, WCSnsABTestActionItem, WCSnsABTestTipData;

@protocol WCTimelineCellABTestTipExt
- (void)handleABTestTipClickEvent:(WCSnsABTestTipData *)arg1 actionItem:(WCSnsABTestActionItem *)arg2 dataItem:(WCDataItem *)arg3;
@end

