//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray;

@protocol WCTimelineDelegate
- (void)onTimelineDataChanged:(NSArray *)arg1 andAdItems:(NSArray *)arg2;
- (void)onNoMoreTimelineData;
- (void)onTimelineDataChangedWithAdded:(NSArray *)arg1 andChanged:(NSArray *)arg2 andDeleted:(NSArray *)arg3;
@end

