//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

#import "EmoticonWebDownloadMgrExt-Protocol.h"

@interface WebviewJSEventHandler_addEmoticon : WebviewJSEventHandlerBase <EmoticonWebDownloadMgrExt>
{
}

- (void)onDownloadFailedWithUrl:(id)arg1 userData:(id)arg2 errType:(int)arg3;
- (void)onDownloadFinishedWithUrl:(id)arg1 userData:(id)arg2;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;
- (void)dealloc;
- (id)init;

@end

