//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 16 2016 16:28:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

#import "IBrandAttrMgrExt-Protocol.h"

@class NSString;

@interface WebviewJSEventHandler_startVoipCall : WebviewJSEventHandlerBase <IBrandAttrMgrExt>
{
    unsigned int _m_uGetContactInfoTryTimes;
    NSString *_m_nsUsername;
    NSString *_m_nsNickname;
    NSString *_m_nsIconUrl;
    NSString *_m_nsAppId;
}

@property(nonatomic) unsigned int m_uGetContactInfoTryTimes; // @synthesize m_uGetContactInfoTryTimes=_m_uGetContactInfoTryTimes;
@property(retain, nonatomic) NSString *m_nsAppId; // @synthesize m_nsAppId=_m_nsAppId;
@property(retain, nonatomic) NSString *m_nsIconUrl; // @synthesize m_nsIconUrl=_m_nsIconUrl;
@property(retain, nonatomic) NSString *m_nsNickname; // @synthesize m_nsNickname=_m_nsNickname;
@property(retain, nonatomic) NSString *m_nsUsername; // @synthesize m_nsUsername=_m_nsUsername;
- (void).cxx_destruct;
- (void)getAndSaveBrandInfo;
- (void)onBrandContactModified:(id)arg1 withAttrChanged:(id)arg2;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

@end

